##print("hello world")
    
# a=20
# b="mango"
# c=5.5
# d=False

# e=int(input("enter the value:"))
# print(type(e))
# print(e)

# addition = a+c
# print(addition)

# a=int(input("enter the value1:"))
# b=input("enter the value2:")

# c=(a) + int(b)
# print("addition of a and b is", c)
# print(type(c))

a= int(input("enter the value1:"))
b=int(input("enter the value2:"))

c=(a)/(b)
print("divition of a and b is",c)
print(type(c))

r=(a)+(b)
print("addition of a and b is",r)
t=(a)-(b)
print("subtraction of a and b is",t)
g=(a)*(b)
print("multiplication of a and b is",g)
s=(a)/(b)
print("divition of a and b is",s)