# name=input("enter the name:")
# print("good morning!",name)

#letter="""dear <|name|>,you are selected!<|date|>."""

# name=input("enter the name:")
# date=input("enter the date:")
# letter=letter.replace("<|name|>",name)
# letter=letter.replace("<|date|>",date)
# print(letter)

# a="  banana"
# r=a.replace("  "," ")
# print(r)
# print(a.strip

# l=["harry","Soham","Sachin","rahul"]

# for i in l:
#     if i.startswith("S"):
#         print("hello"+i)
# x=1
# while x<11:
#     print("n",*"x","=",x*1)

factorial=5
for i in range(1,6):
    factorial*=i
print(factorial)
    



    
         